import type { Metadata } from 'next'

// These styles apply to every route in the application
import '@/styles/global.css'

export const metadata: Metadata = {
    title: 'Product list with cart --- React & Next',
    description: 'Generated by create next app',
    icons: {
        icon: './assets/images/favicon-32x32.png',
    },

}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}